### ISSUE TITLE
failed to create LLB definition

### ISSUE THREAD

**Issue by zongsforce** [afedulov/fraud-detection-demo#10]
hi, when i execute the command, `docker build -t demo-fraud-webapp:latest -f webapp/webapp.Dockerfile webapp/`, it turn out to be an error: 
`failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:31378686fda613ca2a502a1731b12ff2d7a8dacabec2160715ebecb461fd3642: not found`
![image](https://user-images.githubusercontent.com/46927025/125244213-a238f600-e321-11eb-9279-252d5acc654a.png)

my computer is mac, m1, 11.4
i don't know if it is related to this error

**Comment by afedulov** [comment]
Hi @zongsforce ,
what if you try to set those two variables before running the build?
```
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
```

**Comment by afedulov** [comment]
I am going to close this one, I hope you managed to make it work.
