### ISSUE TITLE
Cannot compile with JDK 11

### ISSUE THREAD

**Issue by fpompermaier** [afedulov/fraud-detection-demo#2]
I had to upate Lombok to 1.18.2 to compile successfully, otherwise I have the following problem:

Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]

**Comment by afedulov** [comment]
Hi @fpompermaier. Thanks for reporting. Do you mean you had to downgrade to 1.8.2? Because the current version of Lombok used is 1.8.4.

**Comment by fpompermaier** [comment]
No, I upgraded to 1.**18**.2. This is the diff of my webapp/pom.xml

```
 <dependency>
       <groupId>org.projectlombok</groupId>
       <artifactId>lombok</artifactId>
-      <version>1.16.16</version>
+      <version>1.18.2</version>
       <scope>provided</scope>
 </dependency>

```

**Comment by afedulov** [comment]
Ah, OK, you mean in the webapp, not in the flink-job. Thanks for reporting, I've fixed it.
