### ISSUE TITLE
Execution failed for task ':verifyGoogleJavaFormat'

### ISSUE THREAD

**Issue by doanthuan** [afedulov/fraud-detection-demo#5]
Hi, this error happen again to me but with different file: [https://github.com/afedulov/fraud-detection-demo/issues/1](https://github.com/afedulov/fraud-detection-demo/issues/1)

This is the details:
`Step 10/17 : RUN ./gradlew build
 ---> Running in 90a4f4b0407f
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
:compileJava
:processResources
:classes
:jar
:startScripts UP-TO-DATE
:distTar
:distZip
:shadowJar
:startShadowScripts
:shadowDistTar
:shadowDistZip
:assemble
:compileTestJava
:processTestResources NO-SOURCE
:testClasses
:test
:verifyGoogleJavaFormat

The following files are not formatted properly:

/home/gradle/app/src/main/java/com/ververica/field/dynamicrules/functions/DynamicAlertFunction.java
:verifyGoogleJavaFormat FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyGoogleJavaFormat'.
> Problems: formatting style violations

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
13 actionable tasks: 12 executed, 1 up-to-date
The command '/bin/sh -c ./gradlew build' returned a non-zero code: 1`

**Comment by afedulov** [comment]
Thanks for reporting. The fix is out. Please, re-clone the repository, I had to rewrite the history due an erroneous external contribution that accidentally got merged.
