### ISSUE TITLE
 Why does the stringsStreamToRules method in the RulesSource class use Watermark?

### ISSUE THREAD

**Issue by MOBIN-F** [afedulov/fraud-detection-demo#8]
public static DataStream<Rule> stringsStreamToRules(DataStream<String> ruleStrings) {
    return ruleStrings
        .flatMap(new RuleDeserializer())
        .name("Rule Deserialization")
        .setParallelism(RULES_STREAM_PARALLELISM)
        **.assignTimestampsAndWatermarks(
            new BoundedOutOfOrdernessTimestampExtractor<Rule>(Time.of(0, TimeUnit.MILLISECONDS)) {
              @Override
              public long extractTimestamp(Rule element) {
                // Prevents connected data+update stream watermark stalling.
                return Long.MAX_VALUE;
              }
            });**
  }

**Comment by afedulov** [comment]
@MOBIN-F please ask your question in the discussion thread to the corresponding blog post:
https://flink.apache.org/news/2020/03/24/demo-fraud-detection-2.html and deference the file in this Github repository. Thanks.

**Comment by MOBIN-F** [comment]
@afedulov OK i do it

**Comment by MOBIN-F** [comment]
@afedulov OK i do it

**Comment by MOBIN-F** [comment]
@afedulov OK i do it
